### ISSUE TITLE
add github action jobs for running lint and format

### ISSUE THREAD

**Issue by jbpratt** [piqe-test-libraries/piqe-ocp-lib#58]
A lot of code is slipping by without at least being formatted. This has been addressed in #49 but we need to catch it in PRs using automation as well.

**Comment by Dannyb48** [comment]
@jbpratt 

We do have gh actions that run linting and formating on every PR. 
https://github.com/piqe-test-libraries/piqe-ocp-lib/blob/master/.github/workflows/build.yml#L32

It runs our make file which calls poetry
https://github.com/piqe-test-libraries/piqe-ocp-lib/blob/master/Makefile#L11

It calls flake8, black, and isort

I haven't looked at it since a team member (who is no longer at the company) set it up. I wonder if the configs for these formatting/linting tools are too loose?

**Comment by jbpratt** [comment]
Hey @Dannyb48 I assumed that is what the build jobs do but a lot of code has slipped through which I just simply ran `make format` in this commit https://github.com/piqe-test-libraries/piqe-ocp-lib/pull/49/commits/fe589b9d5bb3adf51df9203837db911529df849c so I think it is worth making sure this is working as intended.

**Comment by Dannyb48** [comment]
@jbpratt I agree!

I just took a look and I think the reason nothing is sticking when it runs the formatting is because there is nothing actually committing it to include it in the PR. Which makes sense why we are seeing things slip through the cracks all the time. 

So I think there a few options:

Option A:
1) We tweak it so that upstream gh actions rather than doing the reformatting, it performs a diff check. So that that the gh actions fail during lint/formatting if something isn't correct. 

2) The the onus would be on the contributor to run the formatter to make sure everything up to snuff as part of their local commit before pushing upstream.

or

Option B:
We test if we can leverage something like pre-commit and see if there is a commit hook already for isort and black so that it in the gh. I don't have a lot of experience with the pre-commit framework but I assume we won't be in the same position we are in now though since it is utilizing git hooks under the cover.

**Comment by jbpratt** [comment]
Hey @Dannyb48, option A seems like the simplest approach, so just run something like `git diff-index --quiet HEAD --` then check the return code.

On the topic of option B, I am an avid user of pre-commit so I'm always open to go down this road. The author is working on a new project that would specifically address this issue. https://pre-commit.ci/ . You can find me utilizing it here on an random project https://github.com/jbpratt/optorset/pull/17 and it is free for public repositories. All it requires is a valid pre-commit config (which you can find mine in the repository linked) and enabling.

**Comment by jbpratt** [comment]
closed with #61
